### ISSUE TITLE
Note: Concourse reuses volumes (and skips get) when re-triggering a build

### ISSUE THREAD

**Issue by itsdalmo** [itsdalmo/github-pr-resource#5]
As the title says, this produced unexpected results when testing this resource by retriggering builds and seeing whether the `potentialMergeCommit` was updated after a push to master. Since `get` was never run and the old volume reused, the new merge commit (after commits to master) was not used when re-triggering the build for a given PR commit.

However, this resource does not really work with retriggered builds since it will always pull the latest commits from **any** pull request, meaning that your PR's version is unlikely to stay the latest version for very long.

**Comment by vito** [comment]
@itsdalmo I think this can be resolved once spaces is out (surprise, surprise).

One of the things it'll allow you to do is perform a `put` which produces a version that is local to the build, i.e. it doesn't muck with the resource's version history. Technically this works because builds just record denormalized version hashes as outputs and then they're correlated to the version history for scheduling purposes, so that the history only comes from `check` (meaning `put`s no longer force versions to appear). So if a `put` just makes up a version that `check` never finds, it has no effect on the rest of the pipeline, but you can still `get` it thanks to the dependent `get`!

Taking advantage of this, you could do something like:

```yaml
- get: pr        # gets {pr: 124, ref: abcdef}
- get: base      # gets {ref: deadbeef}
- put: merged-pr # produces a version like {pr: 124, ref: abcdef, base: deadbeef}
  resource: pr
  params: {merge_base: base, status: pending}
  # implicit get fetches the version against the specified `base`
- # ...
```

This would fix the caching issue by putting the base ref in the version, while also only triggering when PRs change. It'd also be super clear which version is being used as the base.
